name: MVBookPlugin
main: tw.mayortw.mvbook.MVBookPlugin
version: 0.4
description: "Multiverse teleporting book"
author: "R26"
depend:
    - Multiverse-Core

commands:
    mvbook:
        usage: "Usage: /<command>"
        permission: mvbook.use

permissions:
    mvbook.use:
        default: true
