name: MVBookPlugin
main: tw.mayortw.mvbook.MVBookPlugin
version: 0.1
description: "Multiverse teleporting book"
author: "R26"

commands:
    mvbook:
        usage: "Usage: /<command>"
        permission: mvbook.use

permissions:
    mvbook.use:
        default: true
